- name: Upgrade packages
  become: true
  ansible.builtin.apt:
    upgrade: true
    update_cache: true

- name: Install utility packages
  become: true
  ansible.builtin.apt:
    install_recommends: false
    name:
      - wget
      - unzip
      - ansible

- name: Install ssg packages
  become: true
  ansible.builtin.apt:
    install_recommends: false
    name:
      - ssg-base
      - ssg-debderived
      - ssg-debian
      - ssg-nondebian
      - ssg-applications

- name: Install oscap package
  become: true
  ansible.builtin.apt:
    install_recommends: false
    name:
      - libopenscap8
