- name: Upgrade packages
  become: true
  ansible.builtin.apt:
    upgrade: true
    update_cache: true

- name: Install utility packages
  become: true
  ansible.builtin.apt:
    install_recommends: false
    name:
      - wget
      - unzip
      - ansible

- name: Install ssg packages
  become: true
  ansible.builtin.apt:
    install_recommends: false
    name:
      - ssg-base
      - ssg-debderived
      - ssg-debian
      - ssg-nondebian
      - ssg-applications

- name: Install oscap package
  become: true
  ansible.builtin.apt:
    install_recommends: false
    name:
      - libopenscap8

# see https://adamtheautomator.com/openscap/
- name: Download scap security guide
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/ComplianceAsCode/content/releases/download/v0.1.64/scap-security-guide-0.1.64.zip
    dest: /opt/
    remote_src: true
    # validate_certs: no
