- name: Install utility packages
  become: true
  ansible.builtin.apt:
    install_recommends: false
    name:
      - ubuntu-desktop

- name: Setup japanese by command
  become: true
  ansible.builtin.shell:
    cmd: locale-gen ja_JP.UTF-8

- name: Setup japanese to profile
  ansible.builtin.blockinfile:
    path: "{{ (lookup('env', 'HOME')) }}/.profile"
    create: true
    block: export LANG=ja_JP.UTF-8

- name: Setup timezone by command
  become: true
  ansible.builtin.shell:
    cmd: timedatectl set-timezone Asia/Tokyo
