## oscap info /opt/scap-security-guide-0.1.64/ssg-ubuntu2004-ds.xml
# Document type: Source Data Stream
# Imported: 2022-09-30T15:23:16

# Stream: scap_org.open-scap_datastream_from_xccdf_ssg-ubuntu2004-xccdf-1.2.xml
# Generated: (null)
# Version: 1.3
# Checklists:
#         Ref-Id: scap_org.open-scap_cref_ssg-ubuntu2004-xccdf-1.2.xml
#                 Status: draft
#                 Generated: 2022-09-30
#                 Resolved: true
#                 Profiles:
#                         Title: CIS Ubuntu 20.04 Level 1 Server Benchmark
#                                 Id: xccdf_org.ssgproject.content_profile_cis_level1_server
#                         Title: CIS Ubuntu 20.04 Level 1 Workstation Benchmark
#                                 Id: xccdf_org.ssgproject.content_profile_cis_level1_workstation
#                         Title: CIS Ubuntu 20.04 Level 2 Server Benchmark
#                                 Id: xccdf_org.ssgproject.content_profile_cis_level2_server
#                         Title: CIS Ubuntu 20.04 Level 2 Workstation Benchmark
#                                 Id: xccdf_org.ssgproject.content_profile_cis_level2_workstation
#                         Title: Standard System Security Profile for Ubuntu 20.04
#                                 Id: xccdf_org.ssgproject.content_profile_standard
#                         Title: Canonical Ubuntu 20.04 LTS Security Technical Implementation Guide (STIG) V1R1
#                                 Id: xccdf_org.ssgproject.content_profile_stig
#                 Referenced check files:
#                         ssg-ubuntu2004-oval.xml
#                                 system: http://oval.mitre.org/XMLSchema/oval-definitions-5
#                         ssg-ubuntu2004-ocil.xml
#                                 system: http://scap.nist.gov/schema/ocil/2
# Checks:
#         Ref-Id: scap_org.open-scap_cref_ssg-ubuntu2004-oval.xml
#         Ref-Id: scap_org.open-scap_cref_ssg-ubuntu2004-ocil.xml
#         Ref-Id: scap_org.open-scap_cref_ssg-ubuntu2004-cpe-oval.xml
# Dictionaries:
#         Ref-Id: scap_org.open-scap_cref_ssg-ubuntu2004-cpe-dictionary.xml

- name: Evaluate OS
  hosts: all
  tasks:
    - name: Evaluate content_profile_cis_level1_server
      become: true
      ansible.builtin.shell:
        cmd: |
          oscap xccdf eval \
            --results-arf /home/vagrant/ssg-ubuntu2004-content_profile_cis_level1_server-results.xml \
            --report /home/vagrant/ssg-ubuntu2004-content_profile_cis_level1_server-report.html \
            --profile xccdf_org.ssgproject.content_profile_cis_level1_server \
            /opt/scap-security-guide-0.1.64/ssg-ubuntu2004-ds.xml; exit 0

    - name: Evaluate content_profile_cis_level1_workstation
      become: true
      ansible.builtin.shell:
        cmd: |
          oscap xccdf eval \
            --results-arf /home/vagrant/ssg-ubuntu2004-content_profile_cis_level1_workstation-results.xml \
            --report /home/vagrant/ssg-ubuntu2004-content_profile_cis_level1_workstation-report.html \
            --profile xccdf_org.ssgproject.content_profile_cis_level1_workstation \
            /opt/scap-security-guide-0.1.64/ssg-ubuntu2004-ds.xml; exit 0

    - name: Evaluate content_profile_cis_level2_server
      become: true
      ansible.builtin.shell:
        cmd: |
          oscap xccdf eval \
            --results-arf /home/vagrant/ssg-ubuntu2004-content_profile_cis_level2_server-results.xml \
            --report /home/vagrant/ssg-ubuntu2004-content_profile_cis_level2_server-report.html \
            --profile xccdf_org.ssgproject.content_profile_cis_level2_server \
            /opt/scap-security-guide-0.1.64/ssg-ubuntu2004-ds.xml; exit 0

    - name: Evaluate content_profile_cis_level2_workstation
      become: true
      ansible.builtin.shell:
        cmd: |
          oscap xccdf eval \
            --results-arf /home/vagrant/ssg-ubuntu2004-content_profile_cis_level2_workstation-results.xml \
            --report /home/vagrant/ssg-ubuntu2004-content_profile_cis_level2_workstation-report.html \
            --profile xccdf_org.ssgproject.content_profile_cis_level2_workstation \
            /opt/scap-security-guide-0.1.64/ssg-ubuntu2004-ds.xml; exit 0

    - name: Evaluate content_profile_standard
      become: true
      ansible.builtin.shell:
        cmd: |
          oscap xccdf eval \
            --results-arf /home/vagrant/ssg-ubuntu2004-content_profile_standard-results.xml \
            --report /home/vagrant/ssg-ubuntu2004-content_profile_standard-report.html \
            --profile xccdf_org.ssgproject.content_profile_standard \
            /opt/scap-security-guide-0.1.64/ssg-ubuntu2004-ds.xml; exit 0

    - name: Evaluate content_profile_stig
      become: true
      ansible.builtin.shell:
        cmd: |
          oscap xccdf eval \
            --results-arf /home/vagrant/ssg-ubuntu2004-content_profile_stig-results.xml \
            --report /home/vagrant/ssg-ubuntu2004-content_profile_stig-report.html \
            --profile xccdf_org.ssgproject.content_profile_stig \
            /opt/scap-security-guide-0.1.64/ssg-ubuntu2004-ds.xml; exit 0
