## oscap info /opt/scap-security-guide-0.1.64/ssg-ubuntu2004-ds.xml
# Document type: Source Data Stream
# Imported: 2022-09-30T15:23:16

# Stream: scap_org.open-scap_datastream_from_xccdf_ssg-ubuntu2004-xccdf-1.2.xml
# Generated: (null)
# Version: 1.3
# Checklists:
#         Ref-Id: scap_org.open-scap_cref_ssg-ubuntu2004-xccdf-1.2.xml
#                 Status: draft
#                 Generated: 2022-09-30
#                 Resolved: true
#                 Profiles:
#                         Title: CIS Ubuntu 20.04 Level 1 Server Benchmark
#                                 Id: xccdf_org.ssgproject.content_profile_cis_level1_server
#                         Title: CIS Ubuntu 20.04 Level 1 Workstation Benchmark
#                                 Id: xccdf_org.ssgproject.content_profile_cis_level1_workstation
#                         Title: CIS Ubuntu 20.04 Level 2 Server Benchmark
#                                 Id: xccdf_org.ssgproject.content_profile_cis_level2_server
#                         Title: CIS Ubuntu 20.04 Level 2 Workstation Benchmark
#                                 Id: xccdf_org.ssgproject.content_profile_cis_level2_workstation
#                         Title: Standard System Security Profile for Ubuntu 20.04
#                                 Id: xccdf_org.ssgproject.content_profile_standard
#                         Title: Canonical Ubuntu 20.04 LTS Security Technical Implementation Guide (STIG) V1R1
#                                 Id: xccdf_org.ssgproject.content_profile_stig
#                 Referenced check files:
#                         ssg-ubuntu2004-oval.xml
#                                 system: http://oval.mitre.org/XMLSchema/oval-definitions-5
#                         ssg-ubuntu2004-ocil.xml
#                                 system: http://scap.nist.gov/schema/ocil/2
# Checks:
#         Ref-Id: scap_org.open-scap_cref_ssg-ubuntu2004-oval.xml
#         Ref-Id: scap_org.open-scap_cref_ssg-ubuntu2004-ocil.xml
#         Ref-Id: scap_org.open-scap_cref_ssg-ubuntu2004-cpe-oval.xml
# Dictionaries:
#         Ref-Id: scap_org.open-scap_cref_ssg-ubuntu2004-cpe-dictionary.xml

- name: Evaluate OS
  hosts: all
  tasks:
    - name: Create stig directory
      become: true
      ansible.builtin.file:
        path: /opt/stigs/
        state: directory
        mode: '0755'

    - name: Create reports directory
      ansible.builtin.file:
        path: "{{ (lookup('env', 'HOME')) }}/reports"
        state: directory
        mode: '0755'

    # see https://adamtheautomator.com/openscap/
    - name: Download scap security guide
      become: true
      ansible.builtin.unarchive:
        src: https://github.com/ComplianceAsCode/content/releases/download/v0.1.64/scap-security-guide-0.1.64.zip
        dest: /opt/
        remote_src: true

    # see https://adamtheautomator.com/openscap/
    - name: Download scap security guide
      become: true
      ansible.builtin.unarchive:
        src: https://dl.dod.cyber.mil/wp-content/uploads/stigs/zip/U_CAN_Ubuntu_20-04_LTS_V1R4_STIG_SCAP_1-2_Benchmark.zip
        dest: /opt/stigs/
        remote_src: true

    - name: Evaluate by DISA STIG
      become: true
      loop:
        - stig_profile_MAC-1_Classified
        - stig_profile_MAC-1_Public
        - stig_profile_MAC-1_Sensitive
        - stig_profile_MAC-2_Classified
        - stig_profile_MAC-2_Public
        - stig_profile_MAC-2_Sensitive
        - stig_profile_MAC-3_Classified
        - stig_profile_MAC-3_Public
        - stig_profile_MAC-3_Sensitive
        - stig_profile_CAT_I_Only
      ansible.builtin.shell:
        cmd: |
          oscap xccdf eval \
            --results-arf /home/vagrant/reports/{{ item }}-results.xml \
            --report /home/vagrant/reports/{{ item }}-report.html \
            --profile xccdf_mil.disa.{{ item }} \
            /opt/stigs/U_CAN_Ubuntu_20-04_LTS_V1R4_STIG_SCAP_1-2_Benchmark.xml; exit 0

    - name: Evaluate by CIS benchmark
      loop:
        - content_profile_cis_level1_server
        - content_profile_cis_level1_workstation
        - content_profile_cis_level2_server
        - content_profile_cis_level2_workstation
        - content_profile_standard
        - content_profile_stig
      become: true
      ansible.builtin.shell:
        cmd: |
          oscap xccdf eval \
            --results-arf /home/vagrant/reports/ssg-ubuntu2004-{{ item }}-results.xml \
            --report /home/vagrant/reports/ssg-ubuntu2004-{{ item }}-report.html \
            --profile xccdf_org.ssgproject.{{ item }} \
            /opt/scap-security-guide-0.1.64/ssg-ubuntu2004-ds.xml; exit 0
